services:
  - type: web
    name: conecta-saude-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm start
    plan: free
    autoDeploy: true
