import {
  Sector,
  User,
  Channel,
  Conversation,
  Message,
  Announcement,
  EmergencyState,
  Report,
  AuditLog,
  NotificationItem,
} from './types';

export const SEED_SECTORS: Sector[] = [
  {
    id: 'sec-direcao',
    nome: 'Direção Geral e Governança',
    sigla: 'DIRECAO',
    descricao: 'Gestão executiva, regulação central e governança da rede hospitalar.',
    ativo: true,
  },
  {
    id: 'sec-ccdti',
    nome: 'Centro Carioca de Diagnóstico e Tratamento por Imagem',
    sigla: 'CCDTI',
    descricao: 'Unidade especializada em tomografia, ressonância, raio-x e laudos de imagem.',
    ativo: true,
  },
  {
    id: 'sec-cco',
    nome: 'Centro Carioca do Olho',
    sigla: 'CCO',
    descricao: 'Centro oftalmológico de excelência, cirurgias de catarata, retina e córnea.',
    ativo: true,
  },
  {
    id: 'sec-cce',
    nome: 'Centro Carioca de Especialidades',
    sigla: 'CCE',
    descricao: 'Ambulatórios de especialidades médicas, triagem multiprofissional e regulação.',
    ativo: true,
  },
];

export const SEED_USERS: User[] = [
  // ── DIREÇÃO GERAL (Nível 1) ──
  {
    id: 'usr-carlos',
    firebaseUid: 'fb-carlos',
    nome: 'Dr. Carlos Eduardo Mendes',
    email: 'carlos.mendes@saude.rio.br',
    cargo: 'Diretor Geral do Complexo Hospitalar',
    hierarquiaNivel: 1,
    setorId: 'sec-direcao',
    setorNome: 'Direção Geral e Governança',
    ativo: true,
    matricula: 'SUS-88421',
    telefone: '(21) 3111-9001',
    criadoEm: '2026-01-10 08:00',
  },
  {
    id: 'usr-marina',
    firebaseUid: 'fb-marina',
    nome: 'Dra. Marina Albuquerque',
    email: 'marina.albuquerque@saude.rio.br',
    cargo: 'Diretora Adjunta de Operações',
    hierarquiaNivel: 1,
    setorId: 'sec-direcao',
    setorNome: 'Direção Geral e Governança',
    ativo: true,
    matricula: 'SUS-88422',
    telefone: '(21) 3111-9002',
    criadoEm: '2026-01-10 08:30',
  },

  // ── CCDTI (Centro de Imagem) ──
  {
    id: 'usr-juliana',
    firebaseUid: 'fb-juliana',
    nome: 'Dra. Juliana Moreira',
    email: 'juliana.moreira@saude.rio.br',
    cargo: 'Coordenadora Médica de Imagem & Tomografia',
    hierarquiaNivel: 2,
    setorId: 'sec-ccdti',
    setorNome: 'Centro Carioca de Diagnóstico por Imagem (CCDTI)',
    ativo: true,
    matricula: 'SUS-74102',
    telefone: '(21) 3111-9101',
    criadoEm: '2026-01-15 09:00',
  },
  {
    id: 'usr-marcelo',
    firebaseUid: 'fb-marcelo',
    nome: 'Marcelo Pires',
    email: 'marcelo.pires@saude.rio.br',
    cargo: 'Supervisor Técnico de Radiologia',
    hierarquiaNivel: 3,
    setorId: 'sec-ccdti',
    setorNome: 'Centro Carioca de Diagnóstico por Imagem (CCDTI)',
    ativo: true,
    matricula: 'SUS-74105',
    telefone: '(21) 3111-9102',
    criadoEm: '2026-01-15 10:00',
  },
  {
    id: 'usr-lucas',
    firebaseUid: 'fb-lucas',
    nome: 'Lucas Ribeiro',
    email: 'lucas.ribeiro@saude.rio.br',
    cargo: 'Técnico em Radiologia & Tomografia',
    hierarquiaNivel: 4,
    setorId: 'sec-ccdti',
    setorNome: 'Centro Carioca de Diagnóstico por Imagem (CCDTI)',
    ativo: true,
    matricula: 'SUS-74199',
    telefone: '(21) 3111-9103',
    criadoEm: '2026-02-01 07:45',
  },

  // ── CCO (Centro do Olho) ──
  {
    id: 'usr-roberto',
    firebaseUid: 'fb-roberto',
    nome: 'Dr. Roberto Vasconcelos',
    email: 'roberto.vasconcelos@saude.rio.br',
    cargo: 'Coordenador Cirúrgico do CCO',
    hierarquiaNivel: 2,
    setorId: 'sec-cco',
    setorNome: 'Centro Carioca do Olho (CCO)',
    ativo: true,
    matricula: 'SUS-65201',
    telefone: '(21) 3111-9201',
    criadoEm: '2026-01-12 08:15',
  },
  {
    id: 'usr-claudia',
    firebaseUid: 'fb-claudia',
    nome: 'Dra. Claudia Nogueira',
    email: 'claudia.nogueira@saude.rio.br',
    cargo: 'Supervisora de Triagem & Cirurgias',
    hierarquiaNivel: 3,
    setorId: 'sec-cco',
    setorNome: 'Centro Carioca do Olho (CCO)',
    ativo: true,
    matricula: 'SUS-65204',
    telefone: '(21) 3111-9202',
    criadoEm: '2026-01-14 09:30',
  },
  {
    id: 'usr-paula',
    firebaseUid: 'fb-paula',
    nome: 'Paula Souza',
    email: 'paula.souza@saude.rio.br',
    cargo: 'Técnica de Oftalmologia & Acuidade',
    hierarquiaNivel: 4,
    setorId: 'sec-cco',
    setorNome: 'Centro Carioca do Olho (CCO)',
    ativo: true,
    matricula: 'SUS-65299',
    telefone: '(21) 3111-9203',
    criadoEm: '2026-02-05 08:00',
  },

  // ── CCE (Centro de Especialidades) ──
  {
    id: 'usr-beatriz',
    firebaseUid: 'fb-beatriz',
    nome: 'Dra. Beatriz Castro',
    email: 'beatriz.castro@saude.rio.br',
    cargo: 'Coordenadora de Ambulatórios Especializados',
    hierarquiaNivel: 2,
    setorId: 'sec-cce',
    setorNome: 'Centro Carioca de Especialidades (CCE)',
    ativo: true,
    matricula: 'SUS-53101',
    telefone: '(21) 3111-9301',
    criadoEm: '2026-01-18 09:10',
  },
  {
    id: 'usr-renato',
    firebaseUid: 'fb-renato',
    nome: 'Renato Silveira',
    email: 'renato.silveira@saude.rio.br',
    cargo: 'Supervisor de Regulação Ambulatorial',
    hierarquiaNivel: 3,
    setorId: 'sec-cce',
    setorNome: 'Centro Carioca de Especialidades (CCE)',
    ativo: true,
    matricula: 'SUS-53108',
    telefone: '(21) 3111-9302',
    criadoEm: '2026-01-20 11:20',
  },
  {
    id: 'usr-gabriel',
    firebaseUid: 'fb-gabriel',
    nome: 'Gabriel Mendes',
    email: 'gabriel.mendes@saude.rio.br',
    cargo: 'Assistente Técnico de Regulação & SISREG',
    hierarquiaNivel: 4,
    setorId: 'sec-cce',
    setorNome: 'Centro Carioca de Especialidades (CCE)',
    ativo: true,
    matricula: 'SUS-53199',
    telefone: '(21) 3111-9303',
    criadoEm: '2026-02-10 10:15',
  },
];

export const SEED_CHANNELS: Channel[] = [
  {
    id: 'chn-emergencia',
    nome: '🚨 Central de Emergência & Plantão',
    descricao: 'Canal prioritário para códigos de emergência, contingência e acionamento de plantão.',
    tipo: 'emergencia',
    criadoPor: 'usr-carlos',
    ativo: true,
    membrosCount: 11,
    mensagensCount: 14,
    criadoEm: '2026-01-10 08:00',
  },
  {
    id: 'chn-direcao',
    nome: '📢 Avisos Oficiais — Direção Geral',
    descricao: 'Comunicados institucionais compulsórios e diretrizes operacionais de toda a rede.',
    tipo: 'institucional',
    setorId: 'sec-direcao',
    setorSigla: 'DIRECAO',
    criadoPor: 'usr-carlos',
    ativo: true,
    membrosCount: 11,
    mensagensCount: 22,
    criadoEm: '2026-01-10 08:00',
  },
  {
    id: 'chn-ccdti-geral',
    nome: 'CCDTI — Equipe de Imagem & Tomografia',
    descricao: 'Alinhamento operacional de tomografia, radiologia, contrastes e laudos.',
    tipo: 'setor',
    setorId: 'sec-ccdti',
    setorSigla: 'CCDTI',
    criadoPor: 'usr-juliana',
    ativo: true,
    membrosCount: 3,
    mensagensCount: 18,
    criadoEm: '2026-01-15 09:30',
  },
  {
    id: 'chn-cco-geral',
    nome: 'CCO — Equipe Cirúrgica & Ambulatório',
    descricao: 'Coordenação das cirurgias de catarata, blocos cirúrgicos e insumos oftalmológicos.',
    tipo: 'setor',
    setorId: 'sec-cco',
    setorSigla: 'CCO',
    criadoPor: 'usr-roberto',
    ativo: true,
    membrosCount: 3,
    mensagensCount: 15,
    criadoEm: '2026-01-12 09:00',
  },
  {
    id: 'chn-cce-geral',
    nome: 'CCE — Regulação & Especialidades',
    descricao: 'Fluxo de regulação SISREG, consultas ambulatoriais e alocação de especialistas.',
    tipo: 'setor',
    setorId: 'sec-cce',
    setorSigla: 'CCE',
    criadoPor: 'usr-beatriz',
    ativo: true,
    membrosCount: 3,
    mensagensCount: 12,
    criadoEm: '2026-01-18 10:00',
  },
];

export const SEED_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    titulo: 'Protocolo de Higienização e Manutenção do Tomógrafo Aquilion 128',
    mensagem:
      'Em atendimento à resolução RDC 611/2022 da ANVISA, informamos que a manutenção preventiva do tomógrafo Aquilion 128 ocorrerá no próximo sábado das 06:00 às 13:00. Todos os exames eletivos com contraste foram remanejados para a sala 02.',
    prioridade: 'alta',
    criadoPor: 'usr-juliana',
    criadorNome: 'Dra. Juliana Moreira',
    criadorCargo: 'Coordenadora Médica CCDTI',
    publicadoEm: '2026-09-04 14:30',
    ativo: true,
    setorId: 'sec-ccdti',
    lidoPorUserIds: ['usr-carlos', 'usr-marcelo', 'usr-lucas'],
  },
  {
    id: 'ann-2',
    titulo: 'Diretriz Institucional: Obrigatoriedade do Registro de Ocorrências no SUS',
    mensagem:
      'Reiteramos a todos os servidores e colaboradores que qualquer inconformidade assistencial, quebra de equipamento ou incidente com paciente deve ser registrada formalmente nos canais oficiais de ouvidoria em até 24 horas.',
    prioridade: 'urgente',
    criadoPor: 'usr-carlos',
    criadorNome: 'Dr. Carlos Eduardo Mendes',
    criadorCargo: 'Diretor Geral',
    publicadoEm: '2026-09-03 09:15',
    ativo: true,
    lidoPorUserIds: ['usr-carlos', 'usr-juliana', 'usr-roberto', 'usr-beatriz', 'usr-lucas'],
  },
  {
    id: 'ann-3',
    titulo: 'Campanha de Rastreio de Glaucoma e Triagem de Catarata — CCO',
    mensagem:
      'Na próxima terça-feira iniciaremos o mutirão de consultas oftalmológicas de alta precisão. A equipe de técnicos deve conferir os calibradores dos tonômetros até segunda às 17h.',
    prioridade: 'normal',
    criadoPor: 'usr-roberto',
    criadorNome: 'Dr. Roberto Vasconcelos',
    criadorCargo: 'Coordenador Cirúrgico CCO',
    publicadoEm: '2026-09-02 11:00',
    ativo: true,
    setorId: 'sec-cco',
    lidoPorUserIds: ['usr-carlos', 'usr-roberto', 'usr-paula'],
  },
];

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    tipo: 'individual',
    membroIds: ['usr-carlos', 'usr-juliana'],
    ultimaMensagem: 'Doutor, os relatórios de contraste deste mês já foram emitidos.',
    ultimaMensagemHora: '10:45',
    atualizadoEm: '2026-09-05 10:45',
  },
  {
    id: 'conv-2',
    tipo: 'individual',
    membroIds: ['usr-juliana', 'usr-lucas'],
    ultimaMensagem: 'Lucas, por favor confira a calibração do detector da sala 1.',
    ultimaMensagemHora: '09:12',
    atualizadoEm: '2026-09-05 09:12',
  },
  {
    id: 'conv-3',
    tipo: 'individual',
    membroIds: ['usr-roberto', 'usr-paula'],
    ultimaMensagem: 'Paula, os kits descartáveis da facoemulsificação já foram separados?',
    ultimaMensagemHora: '08:30',
    atualizadoEm: '2026-09-05 08:30',
  },
];

export const SEED_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    remetenteId: 'usr-carlos',
    remetenteNome: 'Dr. Carlos Eduardo Mendes',
    remetenteCargo: 'Diretor Geral',
    texto: 'Juliana, bom dia. Como está a fila de espera das tomografias com contraste esta semana?',
    createdAt: '2026-09-05 10:40',
    lida: true,
    tipo: 'texto',
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    remetenteId: 'usr-juliana',
    remetenteNome: 'Dra. Juliana Moreira',
    remetenteCargo: 'Coordenadora Médica CCDTI',
    texto: 'Bom dia, Dr. Carlos. Conseguimos zerar os casos urgentes na quarta-feira. Os relatórios de contraste deste mês já foram emitidos.',
    createdAt: '2026-09-05 10:45',
    lida: true,
    tipo: 'texto',
  },
  {
    id: 'msg-3',
    conversationId: 'conv-2',
    remetenteId: 'usr-juliana',
    remetenteNome: 'Dra. Juliana Moreira',
    remetenteCargo: 'Coordenadora Médica CCDTI',
    texto: 'Lucas, por favor confira a calibração do detector da sala 1.',
    createdAt: '2026-09-05 09:12',
    lida: false,
    tipo: 'texto',
  },
  {
    id: 'msg-ch-1',
    channelId: 'chn-emergencia',
    remetenteId: 'usr-carlos',
    remetenteNome: 'Dr. Carlos Eduardo Mendes',
    remetenteCargo: 'Diretor Geral',
    texto: 'Todos os setores operando dentro do protocolo de contingência nível verde. Em caso de parada ou choque térmico, acionar ramal 1900.',
    createdAt: '2026-09-05 08:00',
    lida: true,
    tipo: 'alerta',
  },
  {
    id: 'msg-ch-2',
    channelId: 'chn-ccdti-geral',
    remetenteId: 'usr-juliana',
    remetenteNome: 'Dra. Juliana Moreira',
    remetenteCargo: 'Coordenadora Médica CCDTI',
    texto: 'Equipe, atenção redobrada na conferência de anamnese de pacientes alérgicos a iodo.',
    createdAt: '2026-09-05 09:30',
    lida: true,
    tipo: 'texto',
  },
];

export const SEED_REPORTS: Report[] = [
  {
    id: 'rep-001',
    autorId: 'usr-lucas',
    autorNome: 'Servidor Identificado',
    denunciadoNome: 'Prestador Terceirizado',
    motivo: 'Descumprimento de protocolo de assepsia no setor de radiologia',
    descricao:
      'Foi observado que a equipe terceirizada de higienização não utilizou os desinfetantes hospitalares preconizados para limpeza da maca do tomógrafo entre os exames.',
    status: 'pendente',
    createdAt: '2026-09-04 16:20',
  },
  {
    id: 'rep-002',
    autorId: 'usr-paula',
    autorNome: 'Relato Confidencial',
    motivo: 'Conduta ríspida com acompanhante idoso na recepção do CCO',
    descricao:
      'Registrado relato anônimo informando falta de paciência no acolhimento de paciente em cadeira de rodas na recepção.',
    status: 'em_analise',
    createdAt: '2026-09-02 11:45',
    observacoes: 'Encaminhado para a gerência de acolhimento humanizado do SUS.',
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    usuarioId: 'usr-carlos',
    usuarioNome: 'Dr. Carlos Eduardo Mendes',
    acao: 'AUTH_LOGIN_SUCCESS',
    modulo: 'Segurança',
    detalhes: 'Login institucional realizado com 2FA ativo no CNES',
    ip: '10.200.12.44',
    createdAt: '2026-09-05 08:02:11',
  },
  {
    id: 'aud-2',
    usuarioId: 'usr-carlos',
    usuarioNome: 'Dr. Carlos Eduardo Mendes',
    acao: 'ANNOUNCEMENT_CREATE',
    modulo: 'Comunicados',
    detalhes: 'Publicação de comunicado prioritário institucional #ann-2',
    ip: '10.200.12.44',
    createdAt: '2026-09-03 09:15:02',
  },
  {
    id: 'aud-3',
    usuarioId: 'usr-juliana',
    usuarioNome: 'Dra. Juliana Moreira',
    acao: 'ANNOUNCEMENT_CREATE',
    modulo: 'Comunicados',
    detalhes: 'Publicação de comunicado setorial CCDTI #ann-1',
    ip: '10.200.15.19',
    createdAt: '2026-09-04 14:30:45',
  },
  {
    id: 'aud-4',
    usuarioId: 'usr-carlos',
    usuarioNome: 'Dr. Carlos Eduardo Mendes',
    acao: 'USER_ROLE_VERIFICATION',
    modulo: 'Governança',
    detalhes: 'Auditoria de privilégios de acesso aos 4 centros hospitalares',
    ip: '10.200.12.44',
    createdAt: '2026-09-05 08:15:20',
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'all',
    titulo: '🚨 Alerta Verde: Protocolo Hospitalar Ativo',
    descricao: 'Equipes de retaguarda em prontidão para regulação de leitos do município.',
    tipo: 'emergencia',
    timestamp: 'Hoje, 08:00',
    lida: false,
  },
  {
    id: 'notif-2',
    userId: 'all',
    titulo: 'Novo Comunicado da Direção Geral',
    descricao: 'Diretriz de notificação compulsória de incidentes no sistema.',
    tipo: 'comunicado',
    timestamp: 'Ontem, 09:15',
    lida: true,
  },
  {
    id: 'notif-3',
    userId: 'usr-lucas',
    titulo: 'Nova mensagem de Dra. Juliana Moreira',
    descricao: 'Lucas, por favor confira a calibração do detector da sala 1.',
    tipo: 'mensagem',
    conversaId: 'conv-2',
    remetenteId: 'usr-juliana',
    timestamp: 'Hoje, 09:12',
    lida: false,
  },
];

export const SEED_EMERGENCY_STATE: EmergencyState = {
  alertActive: false,
  alertMessage: null,
  alertTimestamp: null,
  alertByNome: null,
  alertByCargo: null,
};
